### ISSUE TITLE
Rails 7

### ISSUE THREAD

**Issue by wernerlaude** [kiskolabs/humanizer#56] opened 2023-03-21 11:20 UTC
Hi.. any chance to make it working on Rails 7?
I get => can't modify frozen Hash: {:question=>"Zwei plus zwei?", :answers=>["4", "vier"]}.

Thanks..

**Comment by akonan** [comment] 2023-03-21 13:35
Hello!

Which Ruby version are you using and which Rails? I tested this with ruby 3.0.0 and Rails 7.0.4.3

**Comment by denis-ev** [comment] 2023-06-10 10:35
@akonan I have the same problem, hope this helps.

Cheers

```
About your application's environment
Rails version             7.0.5
Ruby version              ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
RubyGems version          3.4.10
Rack version              2.2.7
JavaScript Runtime        Node.js (V8)
Using humanizer 2.6.4
```

FrozenError in Users#new

can't modify frozen Hash: {:question=>"Two plus two?", :answers=>["4", "four"]}

Extracted source (around line #90):

```
4: <%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
5: <%= render partial: 'form_errors', locals: { what: @user } %>


88: <div class="col-sm-offset-2 col-sm-4">
89: <div class="">CAPTCHA question:</div>
90: <%= f.label :humanizer_answer, @user.humanizer_question, class: '' %>
91: <%= f.text_field :humanizer_answer, class: 'form-control' %>
92: </div>
93: </div>
```


Full Trace
```
humanizer (2.6.4) lib/humanizer.rb:35:in `default_proc='
humanizer (2.6.4) lib/humanizer.rb:35:in `block in humanizer_questions'
humanizer (2.6.4) lib/humanizer.rb:34:in `map'
humanizer (2.6.4) lib/humanizer.rb:34:in `humanizer_questions'
humanizer (2.6.4) lib/humanizer.rb:11:in `humanizer_question'
app/views/users/new.html.erb:90
actionview (7.0.5) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.5) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.5) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.5) lib/action_view/helpers/form_helper.rb:768:in `form_with'
actionview (7.0.5) lib/action_view/helpers/form_helper.rb:460:in `form_for'
app/views/users/new.html.erb:4
actionview (7.0.5) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.5) lib/action_view/base.rb:244:in `_run'
actionview (7.0.5) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.5) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.0.5) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.5) lib/action_view/template.rb:155:in `render'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.5) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.5) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.0.5) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.0.5) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (7.0.5) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.0.5) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (7.0.5) lib/action_view/base.rb:270:in `in_rendering_context'
actionview (7.0.5) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (7.0.5) lib/action_controller/metal/streaming.rb:216:in `_render_template'
actionview (7.0.5) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (7.0.5) lib/action_controller/metal/rendering.rb:158:in `render_to_body'
actionpack (7.0.5) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (7.0.5) lib/abstract_controller/rendering.rb:27:in `render'
actionpack (7.0.5) lib/action_controller/metal/rendering.rb:139:in `render'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
activesupport (7.0.5) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
activerecord (7.0.5) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:21:in `render'
actionpack (7.0.5) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (7.0.5) lib/action_controller/metal/basic_implicit_render.rb:7:in `send_action'
actionpack (7.0.5) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.5) lib/action_controller/metal/rendering.rb:165:in `process_action'
actionpack (7.0.5) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.5) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.5) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.5) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.5) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.5) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.5) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.5) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.5) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.5) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.5) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.5) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.5) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.5) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.5) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.5) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.5) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.5) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.5) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.5) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.5) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.5) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.5) lib/action_dispatch/routing/route_set.rb:852:in `call'
rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.7) lib/rack/etag.rb:27:in `call'
rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.7) lib/rack/head.rb:12:in `call'
actionpack (7.0.5) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.5) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/cookies.rb:704:in `call'
activerecord (7.0.5) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.5) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.5) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.5) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.5) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.5) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.5) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.5) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.5) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.7) lib/rack/method_override.rb:24:in `call'
rack (2.2.7) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.5) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.5) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.5) lib/rails/engine.rb:530:in `call'
thin (1.8.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.8.2) lib/thin/connection.rb:84:in `catch'
thin (1.8.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.8.2) lib/thin/connection.rb:53:in `process'
thin (1.8.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run_machine'
eventmachine (1.2.7) lib/eventmachine.rb:195:in `run'
thin (1.8.2) lib/thin/backends/base.rb:75:in `start'
thin (1.8.2) lib/thin/server.rb:162:in `start'
thin (1.8.2) lib/rack/handler/thin.rb:22:in `run'
rack (2.2.7) lib/rack/server.rb:327:in `start'
railties (7.0.5) lib/rails/commands/server/server_command.rb:38:in `start'
railties (7.0.5) lib/rails/commands/server/server_command.rb:143:in `block in perform'
<internal:kernel>:90:in `tap'
railties (7.0.5) lib/rails/commands/server/server_command.rb:134:in `perform'
thor (1.2.2) lib/thor/command.rb:27:in `run'
thor (1.2.2) lib/thor/invocation.rb:127:in `invoke_command'
thor (1.2.2) lib/thor.rb:392:in `dispatch'
railties (7.0.5) lib/rails/command/base.rb:87:in `perform'
railties (7.0.5) lib/rails/command.rb:48:in `invoke'
railties (7.0.5) lib/rails/commands.rb:18:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
bin/rails:4:in `<main>'
```

User.rb
```
class User < ApplicationRecord
  include Humanizer

...

  # To skip humanizer test for development work by setting this attribute to true.
  attr_accessor :bypass_humanizer
  require_human_on :create, :unless => :bypass_humanizer

...

end
```

**Comment by vesan** [comment] 2023-06-19 14:13
@denis-ev & @wernerlaude I released a new version a moment ago. Can you upgrade to the latest version and try if the problem is fixed for you?

**Comment by denis-ev** [comment] 2023-06-20 09:06
> @denis-ev & @wernerlaude I released a new version a moment ago. Can you upgrade to the latest version and try if the problem is fixed for you?

Thanks @vesan this works perfectly for me now.

**Comment by vesan** [comment] 2023-06-26 13:18
@wernerlaude I'm closing this for now. If you still have an issue with Rails 7, please open a new ticket.

**Closed as completed by vesan** 2023-06-26 13:18 UTC
